### PR TITLE
remove references to master/detail (almost)

### PR DESCRIPTION
**Pull request by lizbur10**

### CODE REVIEW

**Review by ihollander — COMMENTED** [review]
I can't find an industry consensus on an alternative to master/detail, but at least a few articles reference [list/details](https://docs.microsoft.com/en-us/windows/apps/design/controls/list-details) in a similar way. I think list/details is a tad more descriptive than list/item, but I leave the final call up to you!

**Comment by lizbur10** [comment]
I like list/detail - I'll update the lesson to use that. Do you think I should take out master/detail altogether? Or leave the one parenthetical mention?

**Comment by ihollander** [comment]
No, I think leaving it in is important. It's a well-defined industry term so it's better to introduce students to the term and provide an alternative.

**Comment by lizbur10** [comment]
Great - thanks!

**Pull request merged**
